name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./web_app
        run: npm install

      - name: Set permissions
        run: chmod -R 755 ./web_app

      - name: Run lint
        working-directory: ./web_app
        run: npx eslint app.js
        env:
          CI: true

      - name: Run tests
        working-directory: ./web_app
        run: npm test

      - name: Build
        working-directory: ./web_app
        run: npm run build

      - name: Deploy
        uses: actions/checkout@v2
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fiardika-redikru"